/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAnomaliesRouteImport } from './routes/app.anomalies'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppBudgetRouteImport } from './routes/app.budget'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppLivesyncRouteImport } from './routes/app.livesync'
import { Route as AppMoneyleaksRouteImport } from './routes/app.moneyleaks'
import { Route as AppMonitorRouteImport } from './routes/app.monitor'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSimulatorRouteImport } from './routes/app.simulator'
import { Route as AppSmartsaveRouteImport } from './routes/app.smartsave'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAnomaliesRoute = AppAnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppLivesyncRoute = AppLivesyncRouteImport.update({
  id: '/livesync',
  path: '/livesync',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyleaksRoute = AppMoneyleaksRouteImport.update({
  id: '/moneyleaks',
  path: '/moneyleaks',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitorRoute = AppMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulatorRoute = AppSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AppRoute,
} as any)
const AppSmartsaveRoute = AppSmartsaveRouteImport.update({
  id: '/smartsave',
  path: '/smartsave',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/anomalies': typeof AppAnomaliesRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/livesync': typeof AppLivesyncRoute
  '/app/moneyleaks': typeof AppMoneyleaksRoute
  '/app/monitor': typeof AppMonitorRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/smartsave': typeof AppSmartsaveRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/anomalies': typeof AppAnomaliesRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/livesync': typeof AppLivesyncRoute
  '/app/moneyleaks': typeof AppMoneyleaksRoute
  '/app/monitor': typeof AppMonitorRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/smartsave': typeof AppSmartsaveRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/anomalies': typeof AppAnomaliesRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/livesync': typeof AppLivesyncRoute
  '/app/moneyleaks': typeof AppMoneyleaksRoute
  '/app/monitor': typeof AppMonitorRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/smartsave': typeof AppSmartsaveRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/app/alerts'
    | '/app/anomalies'
    | '/app/assistant'
    | '/app/budget'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/insights'
    | '/app/livesync'
    | '/app/moneyleaks'
    | '/app/monitor'
    | '/app/settings'
    | '/app/simulator'
    | '/app/smartsave'
    | '/app/transactions'
    | '/auth/callback'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/app/alerts'
    | '/app/anomalies'
    | '/app/assistant'
    | '/app/budget'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/insights'
    | '/app/livesync'
    | '/app/moneyleaks'
    | '/app/monitor'
    | '/app/settings'
    | '/app/simulator'
    | '/app/smartsave'
    | '/app/transactions'
    | '/auth/callback'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/app/alerts'
    | '/app/anomalies'
    | '/app/assistant'
    | '/app/budget'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/insights'
    | '/app/livesync'
    | '/app/moneyleaks'
    | '/app/monitor'
    | '/app/settings'
    | '/app/simulator'
    | '/app/smartsave'
    | '/app/transactions'
    | '/auth/callback'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/anomalies': {
      id: '/app/anomalies'
      path: '/anomalies'
      fullPath: '/app/anomalies'
      preLoaderRoute: typeof AppAnomaliesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/budget': {
      id: '/app/budget'
      path: '/budget'
      fullPath: '/app/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/livesync': {
      id: '/app/livesync'
      path: '/livesync'
      fullPath: '/app/livesync'
      preLoaderRoute: typeof AppLivesyncRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/moneyleaks': {
      id: '/app/moneyleaks'
      path: '/moneyleaks'
      fullPath: '/app/moneyleaks'
      preLoaderRoute: typeof AppMoneyleaksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitor': {
      id: '/app/monitor'
      path: '/monitor'
      fullPath: '/app/monitor'
      preLoaderRoute: typeof AppMonitorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulator': {
      id: '/app/simulator'
      path: '/simulator'
      fullPath: '/app/simulator'
      preLoaderRoute: typeof AppSimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/smartsave': {
      id: '/app/smartsave'
      path: '/smartsave'
      fullPath: '/app/smartsave'
      preLoaderRoute: typeof AppSmartsaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnomaliesRoute: typeof AppAnomaliesRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppBudgetRoute: typeof AppBudgetRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppLivesyncRoute: typeof AppLivesyncRoute
  AppMoneyleaksRoute: typeof AppMoneyleaksRoute
  AppMonitorRoute: typeof AppMonitorRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSimulatorRoute: typeof AppSimulatorRoute
  AppSmartsaveRoute: typeof AppSmartsaveRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAnomaliesRoute: AppAnomaliesRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppBudgetRoute: AppBudgetRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppLivesyncRoute: AppLivesyncRoute,
  AppMoneyleaksRoute: AppMoneyleaksRoute,
  AppMonitorRoute: AppMonitorRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSimulatorRoute: AppSimulatorRoute,
  AppSmartsaveRoute: AppSmartsaveRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
